version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "game-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-efwo8ysg93nx"
s3_prefix = "game-tracker"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
