AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github.com/TylerStein/gametracker
  
  SAM template for github.com/TylerStein/gametracker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  GameFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/game/
      Handler: game
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /game
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GameTable
      Environment:
        Variables:
          GAME_TABLE_NAME: Game

  GameTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: Game
        PrimaryKey:
          Name: Id
          Type: String


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ServerlessRestApi:
    Description: "API Gateway endpoint URL Game Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/game/"
  GameFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt GameFunction.Arn
  GameFunctionIamRole:
    Description: "Implicit IAM Role created for Game function"
    Value: !GetAtt GameFunctionRole.Arn
